// Replace these values before publishing. The same canonical URL should be used in Cardly's QR and NFC fields.
const profile = { name: "Arnold Bolima", role: "Project Manager", company: "Rebtrade International Corporation", email: "adbolima@rebtrade.com", phone: "+639301143801", website: "https://www.rebtrade.com/", address: "Ortigas Center, Pasig City, Metro Manila", tagline: "Innovative products and services, built on experience, integrity, and excellent workmanship.", photo: "profile.png", accent: "#5f7892" };
const $ = id => document.getElementById(id);
document.title = `${profile.name} · ${profile.company}`;
$("name").textContent = profile.name; $("role").textContent = profile.role; $("companyLarge").textContent = profile.company; $("tagline").textContent = profile.tagline; $("avatar").textContent = profile.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(); document.documentElement.style.setProperty("--accent", profile.accent); if(profile.photo){$("portrait").style.backgroundImage=`url(${profile.photo})`;$("avatar").style.display="none";}
const icon = path => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="${path}"/></svg>`;
const links = [["tel:"+profile.phone,profile.phone,"Work","M6 2h4l2 5-3 2a15 15 0 0 0 6 6l2-3 5 2v4c0 2-2 4-4 4C10 22 2 14 2 6c0-2 2-4 4-4"],["mailto:"+profile.email,profile.email,"Work","M4 4h16v16H4z M4 5l8 6 8-6"],[profile.website,profile.website.replace(/^https?:\/\//,""),"Company","M10 13a5 5 0 0 0 7 0l2-2a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-2 2a5 5 0 0 0 7 7l2-2"],["https://maps.google.com/?q="+encodeURIComponent(profile.address),profile.address,"Office","M12 21s7-6 7-11a7 7 0 1 0-14 0c0 5 7 11 7 11z M12 10a2 2 0 1 0 0 .01"]].filter(x=>x[1]);$("links").innerHTML=links.map(([href,label,meta,path])=>`<a class="link" href="${href}" target="_blank" rel="noopener">${icon(path)}<span><strong>${label}</strong><small>${meta}</small></span></a>`).join("");
const vcard=`BEGIN:VCARD\nVERSION:3.0\nFN:${profile.name}\nORG:${profile.company}\nTITLE:${profile.role}\nEMAIL:${profile.email}\nTEL:${profile.phone}\nURL:${profile.website}\nEND:VCARD`;$('saveContact').href=URL.createObjectURL(new Blob([vcard],{type:'text/vcard'}));
$("share").addEventListener("click",async()=>{try{await navigator.share({title:document.title,text:`${profile.name} · ${profile.role}`,url:location.href})}catch(e){if(e.name!=="AbortError")await navigator.clipboard?.writeText(location.href)}});
